version: '2'
services:
    jhipchat-app:
        image: jhipchat
        external_links:
            - jhipchat-mysql:mysql
            - jhipchat-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipchat?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jhipchat-mysql:
        extends:
            file: mysql.yml
            service: jhipchat-mysql
    jhipchat-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipchat-elasticsearch
