version: '2'
services:
    jhipchat-mysql:
        container_name: jhipchat-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/JHipChat/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipchat
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1
